### ISSUE TITLE
Math Magicians: refactor with hooks❗️❗️

### ISSUE THREAD

**Issue by Feliverse** [Feliverse/Math-Magicians#6]
Hi,
I use **functional components** in Calculator.js, with these characteristics:

1. I create a const where I use a hook: `useState`, It contains the setup characteristics of the component calculate: total, next and operation. to refresh the component when some of them change.
2. I create a constant called `handleClick` to listen to the event click in the button target to inner texts.
3. To show data on the calculator screen, I create a constant screen where validate what kind .
4. I return the section, put all the structure to show in DOM calling the corresponding functions `{screen}` and` {handleClick}.`

**Comment by sumairq** [comment]
### Hi @Feliverse , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete! 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
